import type { Metadata } from "next";
import { Gloock, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const gloock = Gloock({
	subsets: ["latin"],
	weight: "400",
	variable: "--font-gloock",
});

const beVietnamPro = Be_Vietnam_Pro({
	subsets: ["latin"],
	weight: ["400", "500","600", "700"],
	variable: "--font-be-vietnam-pro",
});


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${gloock.variable} ${beVietnamPro.variable} antialiased`}>{children}</body>
		</html>
	);
}
